<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationUrl>http://localhost:5080</ApplicationUrl>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.6">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.3.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../SatellitePipeline.Application/SatellitePipeline.Application.csproj" />
    <ProjectReference Include="../SatellitePipeline.Domain/SatellitePipeline.Domain.csproj" />
    <ProjectReference Include="../SatellitePipeline.Infrastructure/SatellitePipeline.Infrastructure.csproj" />
  </ItemGroup>
</Project>
