<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../SatellitePipeline.Application/SatellitePipeline.Application.csproj" />
    <ProjectReference Include="../SatellitePipeline.Domain/SatellitePipeline.Domain.csproj" />
  </ItemGroup>
</Project>
