<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.6" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../SatellitePipeline.Application/SatellitePipeline.Application.csproj" />
    <ProjectReference Include="../SatellitePipeline.Domain/SatellitePipeline.Domain.csproj" />
    <ProjectReference Include="../SatellitePipeline.Infrastructure/SatellitePipeline.Infrastructure.csproj" />
  </ItemGroup>
</Project>
